<script setup>
	// import ref from vue library to define state objects
	import { ref } from 'vue';

	// state object to show modal defaulted to false
	const showModal = ref(false);
	// state object for new notes
	const newNote = ref('');
	// state object for error messages
	const errorMessage = ref('');
	// state object array for the notes
	const notes = ref([]);

	// function to generate random light color. taken from stackoverflow
	// https://stackoverflow.com/questions/23601792/get-only-light-colors-randomly-using-javascript
	function getRandomColor() {
		return 'hsl(' + Math.random() * 360 + ', 100%, 75%)';
	}

	// handler for adding new notes
	const addNote = () => {
		// validate the length of the note to ensure it is at least 10 characters
		if (newNote.value.length < 10) {
			// note is less than 10 characters. update error message value
			return (errorMessage.value = 'Note needs to be 10 characters or more');
			// exit early and do not process rest of code
		}

		// when called add a new object to the notes array
		notes.value.push({
			// random id number. should be unique
			id: Math.floor(Math.random() * 1000),
			// text taken from newNotes value entered into the textarea
			text: newNote.value,
			// the current date generated using js
			date: new Date(),
			// colour generated by callback function
			color: getRandomColor(),
		});

		// close the modal by setting value to false
		showModal.value = false;
		// reset new note value to empty string
		errorMessage.value = '';
		// reset new note value to empty string
		newNote.value = '';
	};
</script>

<template>
	<main>
		<!-- if showModal state is true then show overlay with modal -->
		<div v-if="showModal" class="overlay">
			<div class="modal">
				<!-- 
          text area bound to newNote state object using two way binding
          trim the value of newNote on input 
        -->
				<textarea v-model.trim="newNote" name="note" id="note" cols="30" rows="10"></textarea>
				<!-- display error message if one is found -->
				<p class="error" v-if="errorMessage">{{ errorMessage }}</p>
				<button @click="addNote">Add Note</button>
				<!-- on button click mutate value of showModal state object to false -->
				<button @click="showModal = false" class="close">Close</button>
			</div>
		</div>

		<div class="container">
			<header>
				<h1>Notes</h1>
				<!-- on button click mutate value of showModal state object to true -->
				<button @click="showModal = true">+</button>
			</header>

			<div class="card-container">
				<!-- 
          use the v-for directive to render a card for each note in the array.
          use style binding to change the background color of the card created.
        -->
				<div v-for="note in notes" :key="note.id" class="card" :style="{ backgroundColor: note.color }">
					<!-- text value of the note from the array -->
					<p class="main-text">{{ note.text }}</p>
					<!-- date value of the note from the array converted to a more user friendly format -->
					<p class="date">{{ note.date.toLocaleDateString('en-US') }}</p>
				</div>
			</div>
		</div>
	</main>
</template>

<style scoped>
	main {
		height: 100vh;
		width: 100vw;
	}

	.container {
		max-width: 1000px;
		padding: 10px;
		margin: 0 auto;
	}

	header {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	h1 {
		font-weight: bold;
		margin-bottom: 25px;
		font-size: 75px;
	}

	header button {
		border: none;
		padding: 10px;
		width: 50px;
		height: 50px;
		cursor: pointer;
		background-color: white;
		border-radius: 100%;
		color: black;
		font-size: 20px;
	}

	.card {
		width: 225px;
		height: 225px;
		background-color: rgb(237, 182, 44);
		padding: 10px;
		border-radius: 15px;
		display: flex;
		flex-direction: column;
		justify-content: space-between;
		margin-right: 20px;
		margin-bottom: 20px;
	}

	.main-text {
		color: black;
	}
	.date {
		font-size: 12.5px;
		font-weight: bold;
		color: black;
	}

	.card-container {
		display: flex;
		flex-wrap: wrap;
	}

	.overlay {
		position: absolute;
		width: 100%;
		height: 100%;
		background-color: rgba(0, 0, 0, 0.77);
		z-index: 10;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.modal {
		width: 750px;
		background-color: white;
		border-radius: 10px;
		padding: 30px;
		position: relative;
		display: flex;
		flex-direction: column;
	}

	.modal button {
		padding: 10px 20px;
		font-size: 20px;
		width: 100%;
		background-color: blueviolet;
		border: none;
		color: white;
		cursor: pointer;
		margin-top: 15px;
	}

	.modal .close {
		background-color: rgb(193, 15, 15);
		margin-top: 7px;
	}

	.modal .error {
		color: rgb(193, 15, 15);
	}
</style>
